"""ตัดคอลัมน์ที่ใช้กับการยืนยันตัวตนด้วย OTP ออก

ทีมตัดสินใจไม่ทำ OTP ในรอบนี้ สมัครแล้วเข้าใช้งานได้ทันที
คอลัมน์ที่เหลือไว้โดยไม่มีอะไรเขียนลงไปจะกลายเป็นข้อมูลตายและทำให้เข้าใจผิด
ถ้าจะทำ OTP ทีหลัง ให้ downgrade กลับ (สร้างคอลัมน์เดิมคืนครบ) หรือดู git history


Revision ID: ec2dff28b63d
Revises: 36a6df1b4452
Create Date: 2026-09-19 15:33:02.377149
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ec2dff28b63d'
down_revision: str | None = '36a6df1b4452'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'verified_at')
    op.drop_column('app_user', 'verification_code')
    op.drop_column('app_user', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('app_user', sa.Column('verification_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('app_user', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
